# Generated by Django 2.2 on 2020-10-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCompany',
            new_name='Company',
        ),
    ]
